package mj.hackpsusp25;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import com.formdev.flatlaf.FlatLightLaf; // Import FlatLaf
import java.util.ArrayList;

public class MainFrame extends javax.swing.JFrame {

    ArrayList<ItemEntry> newItems = new ArrayList<ItemEntry>();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        // Set FlatLaf Look and Feel
        try {
            // Use FlatLaf instead of Nimbus
            UIManager.setLookAndFeel(new FlatLightLaf());
            System.out.println("Current Look and Feel: " + UIManager.getLookAndFeel().getName());
        } catch (Exception e) {
            e.printStackTrace();
        }

        initComponents(); // Initialize UI components
    }
    
    static class ImageRenderer extends DefaultTableCellRenderer {
    @Override
    public void setValue(Object value) {
        if (value instanceof ImageIcon) {
            setIcon((ImageIcon) value);
            setText(""); // Remove text if any
        } else {
            setText(value.toString());
            setIcon(null);
        }
        }
    }

    
    public void rebuildFilterBoxes(){
        ArrayList<String> filters = CategoryQueries.getAllCategories();
        invFilterCmbo.setModel(new javax.swing.DefaultComboBoxModel(filters.toArray()));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Main_Pannel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        But_Shopping_List = new javax.swing.JToggleButton();
        But_Inventory = new javax.swing.JToggleButton();
        But_Add = new javax.swing.JToggleButton();
        But_Sub = new javax.swing.JToggleButton();
        But_Org = new javax.swing.JToggleButton();
        Base_Pannel = new javax.swing.JPanel();
        Inventory_Pannel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        invFilterCmbo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        invTable = new javax.swing.JTable();
        Add_Pannel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        addBarcodeBox = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        addTable = new javax.swing.JTable();
        Sub_Pannel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        subBarcodeBox = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        Org_Pannel = new javax.swing.JPanel();
        Shopping_List_Pannel = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main_Pannel.setBackground(new java.awt.Color(237, 235, 234));
        Main_Pannel.setForeground(new java.awt.Color(220, 220, 220));
        Main_Pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 41, 49));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("AT HOME INVENTORY MANAGMENT SYSTEM");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Main_Pannel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 1180, 90));

        buttonGroup1.add(But_Shopping_List);
        But_Shopping_List.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        But_Shopping_List.setText("Shopping List");
        But_Shopping_List.setBorderPainted(false);
        But_Shopping_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                But_Shopping_ListActionPerformed(evt);
            }
        });
        Main_Pannel.add(But_Shopping_List, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 170, 60));

        buttonGroup1.add(But_Inventory);
        But_Inventory.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        But_Inventory.setText("Inventory");
        But_Inventory.setBorderPainted(false);
        But_Inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                But_InventoryActionPerformed(evt);
            }
        });
        Main_Pannel.add(But_Inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 150, 60));

        buttonGroup1.add(But_Add);
        But_Add.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        But_Add.setText("Add");
        But_Add.setBorderPainted(false);
        But_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                But_AddActionPerformed(evt);
            }
        });
        Main_Pannel.add(But_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 150, 60));

        buttonGroup1.add(But_Sub);
        But_Sub.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        But_Sub.setText("Sub");
        But_Sub.setBorderPainted(false);
        But_Sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                But_SubActionPerformed(evt);
            }
        });
        Main_Pannel.add(But_Sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 150, 60));

        buttonGroup1.add(But_Org);
        But_Org.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        But_Org.setText("Org");
        But_Org.setBorderPainted(false);
        But_Org.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                But_OrgActionPerformed(evt);
            }
        });
        Main_Pannel.add(But_Org, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 150, 60));

        Base_Pannel.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Search: ");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Filters: ");

        invFilterCmbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        invTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Image", "Name", "Quantity", "Filters"
            }
        ));
        jScrollPane1.setViewportView(invTable);

        javax.swing.GroupLayout Inventory_PannelLayout = new javax.swing.GroupLayout(Inventory_Pannel);
        Inventory_Pannel.setLayout(Inventory_PannelLayout);
        Inventory_PannelLayout.setHorizontalGroup(
            Inventory_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventory_PannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invFilterCmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Inventory_PannelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1241, Short.MAX_VALUE))
        );
        Inventory_PannelLayout.setVerticalGroup(
            Inventory_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventory_PannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Inventory_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(invFilterCmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1857, Short.MAX_VALUE))
        );

        Base_Pannel.add(Inventory_Pannel, "card2");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Barcode: ");

        addBarcodeBox.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addBarcodeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBarcodeBoxActionPerformed(evt);
            }
        });

        addTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Image", "Name", "Quantity", "Filters"
            }
        ));
        jScrollPane2.setViewportView(addTable);

        javax.swing.GroupLayout Add_PannelLayout = new javax.swing.GroupLayout(Add_Pannel);
        Add_Pannel.setLayout(Add_PannelLayout);
        Add_PannelLayout.setHorizontalGroup(
            Add_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_PannelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addBarcodeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Add_PannelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1226, Short.MAX_VALUE))
        );
        Add_PannelLayout.setVerticalGroup(
            Add_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_PannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Add_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addBarcodeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1825, Short.MAX_VALUE))
        );

        Base_Pannel.add(Add_Pannel, "card3");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Barcode: ");

        subBarcodeBox.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        subBarcodeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBarcodeBoxActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Image", "Name", "Quantity", "Filters"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout Sub_PannelLayout = new javax.swing.GroupLayout(Sub_Pannel);
        Sub_Pannel.setLayout(Sub_PannelLayout);
        Sub_PannelLayout.setHorizontalGroup(
            Sub_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sub_PannelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subBarcodeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Sub_PannelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1226, Short.MAX_VALUE))
        );
        Sub_PannelLayout.setVerticalGroup(
            Sub_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sub_PannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Sub_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(subBarcodeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1825, Short.MAX_VALUE))
        );

        Base_Pannel.add(Sub_Pannel, "card4");

        javax.swing.GroupLayout Org_PannelLayout = new javax.swing.GroupLayout(Org_Pannel);
        Org_Pannel.setLayout(Org_PannelLayout);
        Org_PannelLayout.setHorizontalGroup(
            Org_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2110, Short.MAX_VALUE)
        );
        Org_PannelLayout.setVerticalGroup(
            Org_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2330, Short.MAX_VALUE)
        );

        Base_Pannel.add(Org_Pannel, "card5");

        jToggleButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jToggleButton1.setText("Edit");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jToggleButton2.setText("Generage");

        jPanel2.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout Shopping_List_PannelLayout = new javax.swing.GroupLayout(Shopping_List_Pannel);
        Shopping_List_Pannel.setLayout(Shopping_List_PannelLayout);
        Shopping_List_PannelLayout.setHorizontalGroup(
            Shopping_List_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Shopping_List_PannelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Shopping_List_PannelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1763, Short.MAX_VALUE))
        );
        Shopping_List_PannelLayout.setVerticalGroup(
            Shopping_List_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Shopping_List_PannelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(Shopping_List_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2272, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Base_Pannel.add(Shopping_List_Pannel, "card6");

        Main_Pannel.add(Base_Pannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 2110, 2330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_Pannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void But_Shopping_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_But_Shopping_ListActionPerformed
        Add_Pannel.setVisible(false);
        Sub_Pannel.setVisible(false);
        Org_Pannel.setVisible(false);
        Shopping_List_Pannel.setVisible(true);
        Inventory_Pannel.setVisible(false);
    }//GEN-LAST:event_But_Shopping_ListActionPerformed

    private void But_InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_But_InventoryActionPerformed
        Add_Pannel.setVisible(false);
        Sub_Pannel.setVisible(false);
        Org_Pannel.setVisible(false);
        Shopping_List_Pannel.setVisible(false);
        Inventory_Pannel.setVisible(true);
        
    }//GEN-LAST:event_But_InventoryActionPerformed

    private void But_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_But_AddActionPerformed
        Add_Pannel.setVisible(true);
        Sub_Pannel.setVisible(false);
        Org_Pannel.setVisible(false);
        Shopping_List_Pannel.setVisible(false);
        Inventory_Pannel.setVisible(false);
    }//GEN-LAST:event_But_AddActionPerformed

    private void But_SubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_But_SubActionPerformed
        Add_Pannel.setVisible(false);
        Sub_Pannel.setVisible(true);
        Org_Pannel.setVisible(false);
        Shopping_List_Pannel.setVisible(false);
        Inventory_Pannel.setVisible(false);
    }//GEN-LAST:event_But_SubActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void addBarcodeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBarcodeBoxActionPerformed
        String barcode = addBarcodeBox.getText();
        try{
            ItemEntry item = BarcodeInterface.getProduct(barcode); 
            boolean itemExists = false;
            
            for(int i=0; i<newItems.size(); i++){
                if(newItems.get(i).getBarcode().equals(barcode)){ //old item, so add quantity
                    itemExists = true;
                    newItems.get(i).setQuantity(newItems.get(i).getQuantity()+1);
                }
            }
            
            if(!itemExists){ //new item
                newItems.add(item);
            }
            
            DefaultTableModel displayClassesTableModel = (DefaultTableModel) addTable.getModel();
            
            displayClassesTableModel.setNumRows(0);
            for (ItemEntry i : newItems) {
                Object[] rowData = new Object[4];
                rowData[0] = null;
                rowData[1] = i.getName();
                rowData[2] = i.getQuantity();
                rowData[3] = null;
                displayClassesTableModel.addRow(rowData);
            }
            
            addBarcodeBox.setText("");
            
        } catch(Exception e){
        
        }
    }//GEN-LAST:event_addBarcodeBoxActionPerformed

    private void subBarcodeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBarcodeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subBarcodeBoxActionPerformed

    private void But_OrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_But_OrgActionPerformed
        Add_Pannel.setVisible(false);
        Sub_Pannel.setVisible(false);
        Org_Pannel.setVisible(true);
        Shopping_List_Pannel.setVisible(false);
        Inventory_Pannel.setVisible(false);
    }//GEN-LAST:event_But_OrgActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add_Pannel;
    private javax.swing.JPanel Base_Pannel;
    private javax.swing.JToggleButton But_Add;
    private javax.swing.JToggleButton But_Inventory;
    private javax.swing.JToggleButton But_Org;
    private javax.swing.JToggleButton But_Shopping_List;
    private javax.swing.JToggleButton But_Sub;
    private javax.swing.JPanel Inventory_Pannel;
    private javax.swing.JPanel Main_Pannel;
    private javax.swing.JPanel Org_Pannel;
    private javax.swing.JPanel Shopping_List_Pannel;
    private javax.swing.JPanel Sub_Pannel;
    private javax.swing.JTextField addBarcodeBox;
    private javax.swing.JTable addTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> invFilterCmbo;
    private javax.swing.JTable invTable;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextField subBarcodeBox;
    // End of variables declaration//GEN-END:variables
}
